name: ldc2
version: 1.1.0
summary: D compiler with LLVM backend
description: |
    LDC is a portable compiler for the D programming Language, with
    modern optimization and code generation capabilities.  It uses
    the official DMD compiler frontend to support the latest version
    of D2, and uses the LLVM Core libraries for code generation.

confinement: classic
grade: devel

apps:
  ldc2:
    command: ldc2
  ldmd2:
    command: ldmd2
  ldc-profdata:
    command: ldc-profdata
  ldc-prune-cache:
    command: ldc-prune-cache

parts:
  ldc:
    source: git://github.com/ldc-developers/ldc.git
    source-tag: v1.1.0
    plugin: cmake
    configflags:
    - -DD_COMPILER=../../ldc-bootstrap/build/bin/ldmd2
    - -DCMAKE_BUILD_TYPE=Release
    - -DLLVM_ROOT_DIR=../../llvm/install
    - -DLDC_INSTALL_LTOPLUGIN=ON
    stage:
    - -etc/ldc2.conf
    build-packages:
    - build-essential
    - libconfig++-dev
    - libedit-dev
    - zlib1g-dev
    stage-packages:
    - libconfig9
    after:
    - ldc-bootstrap
    - llvm
  ldc-config:
    plugin: dump
    source: ldc-config
    organize:
      ldc2.conf: etc/ldc2.conf

  ldc-bootstrap:
    source: git://github.com/ldc-developers/ldc.git
    source-tag: v0.17.3
    plugin: cmake
    configflags:
    - -DCMAKE_BUILD_TYPE=Release
    - -DLLVM_ROOT_DIR=../../llvm/install
    stage:
    - -*
    prime:
    - -*
    build-packages:
    - build-essential
    - libconfig++-dev
    - libedit-dev
    - zlib1g-dev
    stage-packages:
    - libconfig9
    after:
    - llvm

  llvm:
    source: http://releases.llvm.org/3.9.1/llvm-3.9.1.src.tar.xz
    plugin: cmake
    configflags:
    - -DCMAKE_BUILD_TYPE=Release
    - -DLLVM_BINUTILS_INCDIR=/usr/include
    stage:
    - -*
    prime:
    - -*
    build-packages:
    - binutils-dev
    - build-essential
