name: ldc2
version: 1.1.1
summary: D compiler with LLVM backend
description: |
    LDC is a portable compiler for the D programming Language, with
    modern optimization and code generation capabilities.  It uses
    the official DMD compiler frontend to support the latest version
    of D2, and uses the LLVM Core libraries for code generation.

confinement: classic
grade: stable

apps:
  ldc2:
    command: bin/ldc2
  ldmd2:
    command: bin/ldmd2
    aliases: [ldmd2]
  ldc-profdata:
    command: bin/ldc-profdata
    aliases: [ldc-profdata]
  ldc-prune-cache:
    command: bin/ldc-prune-cache
    aliases: [ldc-prune-cache]

parts:
  ldc:
    source: https://github.com/ldc-developers/ldc.git
    source-tag: v1.1.1
    source-type: git
    plugin: cmake
    configflags:
    - -DD_COMPILER=../../ldc-bootstrap/build/bin/ldmd2
    - -DCMAKE_BUILD_TYPE=Release
    - -DCMAKE_C_FLAGS_RELEASE='-O3 -DNDEBUG -Wa,-mrelax-relocations=no'
    - -DLLVM_ROOT_DIR=../../llvm/install
    - -DLDC_INSTALL_LTOPLUGIN=ON
    - -DCMAKE_VERBOSE_MAKEFILE=1
    install: |
      # disable two tests that are problematic on 32-bit
      rm tests/codegen/union.d
      rm tests/PGO/profile_rt_calls.d
      ctest --output-on-failure --verbose -E "std\.net\.curl"
    stage:
    - -etc/ldc2.conf
    build-packages:
    - gcc
    - libconfig++-dev
    - libedit-dev
    - zlib1g-dev
    stage-packages:
    - libconfig9
    after:
    - ctest-setup
    - ldc-bootstrap
    - llvm
  ldc-config:
    plugin: dump
    source: ldc-config
    organize:
      ldc2.conf: etc/ldc2.conf

  ldc-bootstrap:
    source: https://github.com/ldc-developers/ldc.git
    source-tag: v0.17.3
    source-type: git
    plugin: cmake
    configflags:
    - -DCMAKE_BUILD_TYPE=Release
    - -DLLVM_ROOT_DIR=../../llvm/install
    stage:
    - -*
    prime:
    - -*
    build-packages:
    - g++
    - libconfig++-dev
    - libedit-dev
    - zlib1g-dev
    stage-packages:
    - libconfig9
    after:
    - llvm

  llvm:
    source: http://releases.llvm.org/3.9.1/llvm-3.9.1.src.tar.xz
    plugin: cmake
    configflags:
    - -DCMAKE_BUILD_TYPE=Release
    - -DLLVM_BINUTILS_INCDIR=/usr/include
    stage:
    - -*
    prime:
    - -*
    build-packages:
    - binutils-dev
    - g++

  ctest-setup:
    plugin: nil
    stage:
    - -*
    prime:
    - -*
    build-packages:
    - gdb
    - python-pip
    - python-setuptools
    - unzip
    prepare: pip install lit
